#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

# CatSnap keeps build config in an xcconfig, not a .env.
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$REPO_ROOT/CatSnap/CatSnap/CatSnap.xcconfig"
XCODEPROJ="$REPO_ROOT/CatSnap/CatSnap.xcodeproj"
TEAM_ID="DFFRB59G23"
BUNDLE_ID="com.jadaross.CatSnap"
SUPABASE_REF="wgtjtvxpxalyeukgxbpo"

banner "CatSnap → TestFlight"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Accept the App Store Connect Terms of Service"
say "App Store Connect is currently blocked behind a full-page ToS modal."
say "Nothing else works until this is accepted: no app record, no upload,"
say "no TestFlight. This is a legal agreement, so it has to be you."
printf '\n'
open_url "https://appstoreconnect.apple.com/apps"
step "Wait for the 'Terms of Service' dialog to appear."
step "Tick 'I have read and agree to the terms presented above.'"
step "Click the blue 'Agree' button."
step "The page should reload into your (currently empty) Apps list."
printf '\n'
until confirm "Are you through the ToS and looking at the Apps list?"; do
  warn "Can't continue until this is done — everything downstream depends on it."
  note "If Agree stays greyed out, scroll the terms box to the bottom first."
  pause "Press Enter to re-check."
done

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Create the App Store Connect record"
say "This reserves the app so uploaded builds have somewhere to land."
printf '\n'
open_url "https://appstoreconnect.apple.com/apps"
step "Click the blue + button (top-left, next to 'Apps') → 'New App'."
step "Platform:          tick iOS"
step "Name:              CatSnap   (no hyphen)"
step "Primary Language:  English (U.K.) or English (U.S.)"
step "Bundle ID:         pick $BUNDLE_ID from the dropdown"
step "SKU:               CATSNAP001"
step "User Access:       Full Access"
step "Click Create."
printf '\n'
note "If the Bundle ID dropdown is empty, the ToS step above didn't fully"
note "complete — reload the page and check."
printf '\n'
if confirm "Is the CatSnap app record created?"; then
  say "Good — builds will now have somewhere to appear."
else
  SKIPPED+=("Create the App Store Connect app record")
  warn "Skipped — you cannot upload a build until this exists."
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Declare EU Digital Services Act trader status"
say "App Store Connect → Business shows a RED banner: trader status is not"
say "declared. Your account distributes to 175 countries, which includes the"
say "EU, and the DSA requires Apple to verify and publicly display trader"
say "contact details for anyone distributing there."
printf '\n'
warn "Undeclared = your app cannot be made available in the EU at all."
printf '\n'
open_url "https://appstoreconnect.apple.com/business"
step "Click 'Complete Compliance Requirements' in the red banner."
step "Answer whether you are acting as a trader."
note "  Roughly: 'trader' means distributing commercially rather than as a"
note "  hobbyist. A free app with no revenue is often non-trader, but this is"
note "  a legal declaration about YOUR circumstances — read Apple's guidance"
note "  and answer for your own situation. Do not guess."
step "If you declare as a trader, supply the contact details Apple will"
step "  publish on your App Store listing (address, phone, email)."
step "Submit."
printf '\n'
note "The address on file is currently: 17 Sovereign Mews, London E2 8ER."
note "Whatever you enter here becomes PUBLIC on your store listing."
printf '\n'
if confirm "Is trader status declared (red banner gone)?"; then
  say "EU distribution unblocked."
else
  SKIPPED+=("Declare DSA trader status — required for EU availability")
  warn "You can still upload to TestFlight, but not ship to the EU."
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Register your iPhone"
say "Your Apple team has ZERO registered devices right now, so Xcode cannot"
say "generate a provisioning profile. Archiving fails with:"
note "  'Your team has no devices from which to generate a provisioning profile'"
printf '\n'
step "Plug your iPhone into this Mac with a cable."
step "Unlock the phone and tap 'Trust This Computer' if prompted."
step "In Xcode: Window → Devices and Simulators (⇧⌘2)."
step "Your iPhone should appear in the left sidebar."
step "If it shows 'Register Device', click it."
printf '\n'
open_url "https://developer.apple.com/account/resources/devices/list"
say "The page just opened lists your registered devices."
printf '\n'
if confirm "Does your iPhone now appear in that list?"; then
  say "Provisioning will work now."
else
  SKIPPED+=("Register your iPhone at developer.apple.com → Devices")
  warn "Archiving will likely fail until a device is registered."
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Sentry DSN (optional, but do it before you build)"
say "The Sentry SDK is wired up, but no DSN is configured — so crash"
say "reporting silently does nothing. Without it, TestFlight flies blind."
say "The DSN is baked in at build time, so set it BEFORE archiving."
printf '\n'
if confirm "Do you want to configure Sentry now? (No = skip)"; then
  open_url "https://sentry.io/settings/projects/"
  step "Pick (or create) your CatSnap iOS project."
  step "Go to: Settings → Client Keys (DSN)."
  step "Copy the DSN — it looks like https://abc123@o1234.ingest.sentry.io/5678"
  printf '\n'
  ask SENTRY_DSN_RAW "Paste the Sentry DSN:"
  if [[ -n "${SENTRY_DSN_RAW:-}" ]]; then
    # xcconfig treats '//' as a comment. The repo's own example file works
    # around this with $() — an empty substitution that keeps the slashes
    # intact. Apply the same escape, or everything after https: is eaten.
    SENTRY_DSN_ESCAPED=$(printf '%s' "$SENTRY_DSN_RAW" | sed 's|://|:/$()/|')
    write_env SENTRY_DSN "$SENTRY_DSN_ESCAPED"
    note "escaped for xcconfig as: $SENTRY_DSN_ESCAPED"
  else
    SKIPPED+=("Sentry DSN (add SENTRY_DSN to CatSnap.xcconfig)")
    warn "Nothing pasted — skipping."
  fi
else
  SKIPPED+=("Sentry DSN (add SENTRY_DSN to CatSnap.xcconfig)")
  note "Skipped. The app handles a missing DSN gracefully."
fi

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Supabase SMTP"
say "Email confirmation is ON, but no SMTP provider is wired up. Supabase's"
say "built-in SMTP is heavily rate-limited and lands in spam — your first"
say "testers may never receive their confirmation email."
printf '\n'
open_url "https://supabase.com/dashboard/project/$SUPABASE_REF/auth/smtp"
step "Toggle on 'Enable Custom SMTP'."
step "Sign up at resend.com (free tier) if you have no provider yet."
step "Host: smtp.resend.com   Port: 465   Username: resend"
step "Password: your Resend API key."
step "Sender email: something on a domain you control (e.g. catsnap.app)."
step "Sender name: CatSnap"
step "Click Save."
printf '\n'
note "Resend needs you to verify the sending domain via DNS records first."
printf '\n'
if confirm "Is custom SMTP configured?"; then
  say "Confirmation emails should now deliver properly."
else
  SKIPPED+=("Supabase custom SMTP (confirmation emails may go to spam)")
  note "Fine to defer for internal testing — fix before external testers."
fi

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Archive and upload from Xcode"
say "This must go through the Xcode GUI. Automatic signing cannot be driven"
say "from the command line, so there is no scriptable path here."
say "Xcode will create your Apple Distribution certificate along the way —"
say "you only have a Development one today."
printf '\n'
open_url "$XCODEPROJ"
step "Wait for Xcode to finish resolving Swift packages."
step "Set the run destination (top toolbar) to 'Any iOS Device (arm64)'."
note "  Not a simulator — Archive is disabled while a simulator is selected."
step "Product → Archive.  (takes a few minutes)"
step "When the Organizer opens: click 'Distribute App'."
step "Choose 'App Store Connect' → Next."
step "Choose 'Upload' → Next."
step "Leave the default signing options → Next → Upload."
printf '\n'
note "Signing should resolve automatically for team $TEAM_ID."
note "If you hit 'no profiles found', go back and finish stage 3."
printf '\n'
if confirm "Did the upload finish successfully?"; then
  say "Build is on its way to App Store Connect."
else
  SKIPPED+=("Archive + upload the build from Xcode")
  warn "Nothing will appear in TestFlight until this succeeds."
fi

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Confirm the build in TestFlight"
say "Apple processes the upload for 5-15 minutes before it appears."
printf '\n'
open_url "https://appstoreconnect.apple.com/apps"
step "Open CatSnap → TestFlight tab."
step "Wait for the build to move from 'Processing' to 'Ready to Submit'."
printf '\n'
note "You should NOT be asked about export compliance — this repo already"
note "declares ITSAppUsesNonExemptEncryption = false in Info.plist."
printf '\n'
step "Add yourself under 'Internal Testing' → install via the TestFlight app."
printf '\n'
if confirm "Is the build showing in TestFlight?"; then
  say "You're on TestFlight. Daily-drive it and seed some real cat data."
else
  SKIPPED+=("Verify the build lands in TestFlight")
  note "If it never appears, check email — Apple sends rejection reasons there."
fi

finish

printf '  %sStill ahead, once you have real data in the app:%s\n' "$BOLD" "$RESET"
note "  - Screenshots at 6.9in (1320x2868) — iPhone 17 Pro Max, NOT 6.7in"
note "  - Description (4000 char) + keywords (100 char)"
note "  - App Privacy nutrition labels: email, photos, coarse location,"
note "    user content — all linked to identity; no tracking"
note "  - Support URL: https://jadaross.github.io/cat-snap/"
note "  - Privacy URL: https://jadaross.github.io/cat-snap/privacy-policy.html"
printf '\n'
